export enum CorrectionStatus {
    NOT_STARTED = 'NOT_STARTED',
    DOING_RAG = 'DOING_RAG',
    COMPANY_INSIGHT = 'COMPANY_INSIGHT',
    GENERATING = 'GENERATING',
    DONE = 'DONE',
    FAILED = 'FAILED',
}
