export enum BlockKind {
    GROUP_UNCATEGORIZED = 'GROUP_UNCATEGORIZED',
    GROUP = 'GROUP',
    EXPERIENCE = 'EXPERIENCE',
    SECTION_DETAIL = 'SECTION_DETAIL',
    SECTION_ACHIEVEMENT = 'SECTION_ACHIEVEMENT',
    SECTION_TASK = 'SECTION_TASK',
    SECTION_PROBLEM_SOLVING = 'SECTION_PROBLEM_SOLVING',
    SECTION_LEARNING = 'SECTION_LEARNING',
    CONTENT = 'CONTENT',
}
