export enum ErrorCode {
    //공통
    BAD_REQUEST = 'COMMON400',
    UNAUTHORIZED = 'COMMON401',
    INTERNAL_SERVER_ERROR = 'COMMON500',
    NOT_IMPLEMENTED = 'COMMON501',

    //Auth
    ALREADY_VERIFY_USER = 'AUTH409',
    SMS_CODE_NOT_FOUND = 'AUTH_CODE404',
    SMS_CODE_MISMATCH = 'AUTH_CODE400',
    REFRESH_TOKEN_EXPIRED = 'AUTH4011',
    REFRESH_TOKEN_MISSING = 'AUTH4012',
    INVALID_REFRESH_TOKEN = 'AUTH4013',

    //User
    USER_NOT_FOUND = 'USER404',

    //Credit
    INSUFFICIENT_CREDITS = 'CREDIT402',

    //Insight-Log
    NOT_LOG_OWNER = 'LOG403',
    LOG_NOT_FOUND = 'LOG404',
    DUPLICATE_LOG_NAME = 'LOG409',
    ACTIVITY_NOT_FOUND = 'ACTIVITY404',
    DUPLICATE_ACTIVITY_NAME = 'ACTIVITY4091',
    FULL_ACTIVITY_NAME = 'ACTIVITY4092',

    //Experience
    EXPERIENCE_NOT_FOUND = 'EXPERIENCE404',
    DUPLICATE_EXPERIENCE_NAME = 'EXPERIENCE4091',
    EXPERIENCE_MAX_LIMIT = 'EXPERIENCE4092',

    //Portfolio
    PORTFOLIO_NOT_FOUND = 'PORTFOLIO404',
    PORTFOLIO_NOT_EMPTY = 'PORTFOLIO409',

    //Portfolio-Correction
    CORRECTION_NOT_FOUND = 'CORRECTION404',
    CORRECTION_MAX_LIMIT = 'CORRECTION4091',
    CORRECTION_BLOCK_LIMIT_EXCEEDED = 'CORRECTION4092',

    //Ticket
    TICKET_NOT_FOUND = 'TICKET404',
    TICKET_PRODUCT_NOT_FOUND = 'TICKET_PRODUCT404',

    //Payment
    PAYMENT_NOT_FOUND = 'PAYMENT404',
    PAYMENT_NOT_OWNER = 'PAYMENT403',

    //Event
    EVENT_NOT_FOUND = 'EVENT404',
    EVENT_PARTICIPATION_NOT_FOUND = 'EVENT_PARTICIPATION404',
}
