export enum ErrorCode {
    //공통
    BAD_REQUEST = 'COMMON400',
    UNAUTHORIZED = 'COMMON401',
    INTERNAL_SERVER_ERROR = 'COMMON500',
    NOT_IMPLEMENTED = 'COMMON501',

    //Auth
    ALREADY_VERIFY_USER = 'AUTH409',
    SMS_CODE_NOT_FOUND = 'AUTH_CODE404',
    SMS_CODE_MISMATCH = 'AUTH_CODE400',
    INVALID_SOCIAL_PROFILE = 'AUTH4001',
    REFRESH_TOKEN_EXPIRED = 'AUTH4011',
    REFRESH_TOKEN_MISSING = 'AUTH4012',
    INVALID_REFRESH_TOKEN = 'AUTH4013',
    DEACTIVATED_USER = 'AUTH4014',
    SOCIAL_UNLINK_FAILED = 'AUTH5021',

    //User
    USER_NOT_FOUND = 'USER404',

    //Insight-Log
    NOT_LOG_OWNER = 'LOG4031',
    NOT_ACTIVITY_TAG_OWNER = 'ACTIVITY4032',
    LOG_NOT_FOUND = 'LOG404',
    DUPLICATE_LOG_NAME = 'LOG4091',
    LOG_MAX_LIMIT = 'LOG4092',
    ACTIVITY_NOT_FOUND = 'ACTIVITY404',
    DUPLICATE_ACTIVITY_NAME = 'ACTIVITY4091',
    FULL_ACTIVITY_TAG = 'ACTIVITY4092',

    //Experience
    EXPERIENCE_NOT_FOUND = 'EXPERIENCE404',
    DUPLICATE_EXPERIENCE_NAME = 'EXPERIENCE4091',
    EXPERIENCE_MAX_LIMIT = 'EXPERIENCE4092',
    EXPERIENCE_SESSION_ALREADY_EXISTS = 'EXPERIENCE4093',

    INTERVIEW_SESSION_NOT_INITIALIZED = 'INTERVIEW4001',
    INTERVIEW_AI_RELAY_FAILED = 'INTERVIEW5021',

    //Portfolio
    PORTFOLIO_NOT_FOUND = 'PORTFOLIO404',
    PORTFOLIO_NOT_EMPTY = 'PORTFOLIO409',
    PORTFOLIO_EXTRACT_FAILED = 'PORTFOLIO502',

    //Portfolio-Correction
    CORRECTION_NOT_FOUND = 'CORRECTION404',
    CORRECTION_MAX_LIMIT = 'CORRECTION4091',
    CORRECTION_BLOCK_LIMIT_EXCEEDED = 'CORRECTION4092',
    COMPANY_INSIGHT_ALREADY_EXISTS = 'CORRECTION4093',
    COMPANY_INSIGHT_NOT_READY = 'CORRECTION4094',
    CORRECTION_INVALID_STATUS_TRANSITION = 'CORRECTION4221',
    CORRECTION_AI_RELAY_FAILED = 'CORRECTION5021',

    //Ticket
    TICKET_NOT_FOUND = 'TICKET404',
    TICKET_PRODUCT_NOT_FOUND = 'TICKET_PRODUCT404',
    INSUFFICIENT_TICKETS = 'TICKET402',

    //Payment
    PAYMENT_NOT_FOUND = 'PAYMENT404',
    PAYMENT_NOT_OWNER = 'PAYMENT403',
    PAYMENT_ALREADY_PAID = 'PAYMENT4091',
    PAYMENT_CANCEL_NOT_ALLOWED = 'PAYMENT4092',
    PAYMENT_WEBHOOK_INVALID = 'PAYMENT400',
    PAYMENT_EXTERNAL_API_FAILED = 'PAYMENT502',

    //Event
    EVENT_NOT_FOUND = 'EVENT404',
    EVENT_PARTICIPATION_NOT_FOUND = 'EVENT_PARTICIPATION404',
    EVENT_NOT_ACTIVE = 'EVENT4001',
    EVENT_REWARD_ALREADY_GRANTED = 'EVENT4091',
    EVENT_FEEDBACK_ALREADY_PROCESSED = 'EVENT4092',
    EVENT_MANUAL_REWARD_NOT_ALLOWED = 'EVENT4002',
    EVENT_REWARD_NOT_CLAIMABLE = 'EVENT4003',
}
