export enum ErrorCode {
    //공통
    BAD_REQUEST = 'COMMON400',
    UNAUTHORIZED = 'COMMON401',
    INTERNAL_SERVER_ERROR = 'COMMON500',
    NOT_IMPLEMENTED = 'COMMON501',

    //Auth
    ALREADY_VERIFY_USER = 'AUTH409',
    SMS_CODE_NOT_FOUND = 'AUTH_CODE404',
    SMS_CODE_MISMATCH = 'AUTH_CODE400',

    //Credit
    INSUFFICIENT_CREDITS = 'CREDIT402',

    //Insight-Log
    LOG_NOT_FOUND = 'LOG404',
    DUPLICATE_LOG_NAME = 'LOG409',
    ACTIVITY_NOT_FOUND = 'ACTIVITY404',
    DUPLICATE_ACTIVITY_NAME = 'ACTIVITY4091',
    FULL_ACTIVITY_NAME = 'ACTIVITY4092',

    //Experience
    EXPERIENCE_NOT_FOUND = 'EXPERIENCE404',
    DUPLICATE_EXPERIENCE_NAME = 'EXPERIENCE4091',
    EXPERIENCE_MAX_LIMIT = 'EXPERIENCE4092',

    //Portfolio
    PORTFOLIO_NOT_FOUND = 'PORTFOLIO404',

    //Portfolio-Correction
    CORRECTION_NOT_FOUND = 'CORRECTION404',
    CORRECTION_MAX_LIMIT = 'CORRECTION4091',
    CORRECTION_BLOCK_LIMIT_EXCEEDED = 'CORRECTION4092',
}
