CREATE TABLE IF NOT EXISTS correction_portfolio_selection (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    portfolio_correction_id integer NOT NULL,
    portfolio_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_correction_portfolio_selection_correction_portfolio
        UNIQUE (portfolio_correction_id, portfolio_id),
    CONSTRAINT fk_correction_portfolio_selection_correction
        FOREIGN KEY (portfolio_correction_id)
        REFERENCES portfolio_correction (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_correction_portfolio_selection_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_correction_portfolio_selection_correction_id
    ON correction_portfolio_selection (portfolio_correction_id);

CREATE INDEX IF NOT EXISTS idx_correction_portfolio_selection_portfolio_id
    ON correction_portfolio_selection (portfolio_id);

CREATE INDEX IF NOT EXISTS idx_correction_portfolio_selection_correction_active
    ON correction_portfolio_selection (portfolio_correction_id, is_active);
