-- ============================================================
-- 1. term 테이블 생성 (약관 마스터)
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'term_term_type_enum'
          AND n.nspname = current_schema()
    ) THEN
        CREATE TYPE term_term_type_enum AS ENUM ('SERVICE', 'PRIVACY', 'MARKETING');
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS term (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    term_type term_term_type_enum NOT NULL,
    version varchar(10) NOT NULL,
    is_required boolean NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

-- ============================================================
-- 2. 기존 user_agreement 데이터 → term 테이블로 시드
--    (term_type + version 조합별로 term 레코드 생성)
-- ============================================================
INSERT INTO term (term_type, version, is_required, is_active)
SELECT DISTINCT
    ua.term_type::text::term_term_type_enum,
    ua.version,
    CASE WHEN ua.term_type::text IN ('SERVICE', 'PRIVACY') THEN true ELSE false END,
    true
FROM user_agreement ua
WHERE NOT EXISTS (
    SELECT 1 FROM term t
    WHERE t.term_type::text = ua.term_type::text
      AND t.version = ua.version
)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 3. user_agreement 에 term_id 컬럼 추가
-- ============================================================
ALTER TABLE user_agreement
    ADD COLUMN IF NOT EXISTS term_id integer;

-- ============================================================
-- 4. 기존 데이터의 term_id 채우기 (term_type + version 매칭)
-- ============================================================
UPDATE user_agreement ua
SET term_id = t.id
FROM term t
WHERE t.term_type::text = ua.term_type::text
  AND t.version = ua.version
  AND ua.term_id IS NULL;

-- ============================================================
-- 5. term_id NOT NULL 제약 + FK 설정
-- ============================================================
ALTER TABLE user_agreement
    ALTER COLUMN term_id SET NOT NULL;

ALTER TABLE user_agreement
    ADD CONSTRAINT fk_user_agreement_term
        FOREIGN KEY (term_id)
        REFERENCES term (id)
        ON DELETE RESTRICT;

-- ============================================================
-- 6. 기존 인덱스 제거 + 새 unique 인덱스 생성
-- ============================================================
DROP INDEX IF EXISTS "IDX_ab2f57a1554d80897ed179bf001";
DROP INDEX IF EXISTS "IDX_ab2f57a1554d80897ed179bf00";

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_agreement_user_id_term_id
    ON user_agreement (user_id, term_id);

-- ============================================================
-- 7. 레거시 컬럼 제거 (term_type, version)
-- ============================================================
ALTER TABLE user_agreement
    DROP COLUMN IF EXISTS term_type,
    DROP COLUMN IF EXISTS version;

-- 레거시 enum 제거
DROP TYPE IF EXISTS user_agreement_term_type_enum;
